pluma/schema/dataset.py
pluma/stream/__init__.py
pluma/stream/ubx.py

Closes #4 
Adds the method to `Dataset` class to reload ( `dataset.reload_streams()` ) all the streams in the schema.
Eg.:
```python
stream_root_folder = r"path"
dataset = Dataset(stream_root_folder, datasetlabel='label', georeference= Georeference())
dataset.populate_streams(autoload = False)
dataset.streams.UBX.autoload=True
dataset.reload_streams(force_load=False)
dataset.export_streams()
```

Add method to reload dataset schema

---

pluma/schema/dataset.py
pluma/stream/__init__.py
pluma/stream/accelerometer.py
pluma/stream/empatica.py
pluma/stream/georeference.py
pluma/stream/harp.py
pluma/stream/microphone.py
pluma/stream/ubx.py
pluma/sync/__init__.py
pluma/sync/ubx2harp.py

This PR generalizes the synchronization across devices by implementing a ClockReferencing class.
The class instantiates a `conversion_model` and keeps track of the expected input and output of the transformation.
The synchronization of the UBX to Harp has been refactored to reflect this change.
In the future, this class will also be used to modify all streams of a given reference (e.g. Harp) to another temporal reference (e.g. GNSS-UTC)
closes #11

11 clock reference

---

pluma/export/sdi.py
pluma/export/streams.py
pluma/io/accelerometer.py
pluma/schema/__init__.py
pluma/stream/__init__.py
pluma/stream/accelerometer.py
pluma/stream/eeg.py
pluma/stream/empatica.py
pluma/stream/georeference.py
pluma/stream/harp.py
pluma/stream/microphone.py
pluma/stream/ubx.py
pluma/sync/__init__.py

This PR refactors the export SDI and other dataset methods to allow rereferencing the exported dataset time attribute to UBX in cases where an explicit offset was not provided at acquisition time.
None of the time relations between hardware events is changed. The exported rereferenced time is simply a fixed offset applied from the default Harp clock to match the timestamp of the first UBX position data frame. This option should only be used when exporting datasets where the acquisition system hardware clock was not set to the current UTC time.
Usage example:
```python
sdi = dataset.convert_to_sdi(rereference_to_ubx_time=True)
```
Terminology on a few classes and streams was also updated for clarity.

Add support for rereferencing exported dataset time attribute

---

pluma/export/sdi.py

Keep frame time as primary index to preserve sampling frequency information.

Keep exported frame time as primary index

---

pluma/export/ogcapi/features.py
pluma/export/streams.py

Ensure exporting the dataset as a `GeoDataFrame` follows OGC API naming conventions, specifically ensuring the CRS is included whenever it is available and using a snake case naming style for data attributes.

Improve compliance with OGC API features

---

pluma/export/ogcapi/records.py
pluma/export/streams.py
pluma/templates/metadata_template.j2
pyproject.toml

This PR adds support for easily defining OGC API metadata records directly from a dataset. The new class `DatasetRecord` can be used to initialize all metadata properties which can be directly inferred from the dataset itself. Several other properties specified by the OGC API - Records specification can be added using the `RecordProperties` class.

Allow creating an OGC API metadata record directly from a dataset

---

pluma/export/ogcapi/features.py
pluma/io/accelerometer.py

To avoid conflicting dot notation with JSON objects, data frame column names have been renamed to use `_` as hierarchy separator. The exported geoframe also avoids duplicating stream labels in cases where the device name is the same.

Improve compatibility of frame column naming conventions

---

pluma/templates/metadata_template.j2

This PR removes the first two self-reference links from the JSON metadata template. The format specification was incorrect and they are added automatically by the hosting service, so better to leave them undefined.

Remove redundant self-links

---

.gitignore
pluma/io/glia.py
pluma/schema/vr.py
pluma/stream/__init__.py
pluma/stream/csv.py
pluma/stream/glia.py

This PR adds a new stream class: GliaStream which allows a dataset to read Unity data streams for pluma VR experiments.
These streams are usually transmitted from Unity to Bonsai via 0MQ, and then logged as individual 0MQ messages and ~~serialized into a binary file as sequences of messages containing a null terminated string specifying the sensor name followed by the data payload~~ serialized into several frames containing (in order) message topic (i.e. sensor); timestamps; data payload. The GliaStream class can be used to read any streams of this kind by providing format labels ~~as a char array input argument. The format characters follow the python struct convention detailed here https://docs.python.org/3/library/struct.html#format-characters~~ as lists of tuples with the form …

 Add new streams, io and schema for VR experiments

---

pluma/schema/__init__.py
pluma/sync/plotting.py
pluma/sync/ubx2harp.py

This PR externalizes the clock calibration diagnosis plot, to allow customizing figure sizes and axes. Intermediate data structures can be extracted from the low-level calibration routines to provide the required data for custom plotting layouts.

Externalize clock calibration diagnosis plot

---

pluma/export/maps.py

Adds new keyword arguments to `showmap` to allow specifying an existing figure and axes over which to draw the map. This can be useful when building custom grid spec layouts for figures or building other custom visualizations.

Allow plotting map over custom figure and axes

---

pluma/export/maps.py

Enforcing an aspect ratio may cause the extents of the path to fall out of the figure, hiding parts of the data. We do want scaling however to make sure there is some margin around the path extents.
By default `tilemapbase` already computes aspect ratio automatically so we are leaving it to a default of `None` so we can assign scaling independently.

Use automatic aspect ratio by default

---

pluma/export/maps.py

Being able to format the custom colorbar in `showmaps` is useful for specific data types such as dates and times. This PR forwards the `kwargs` of `showmaps` to the `colorbar` call to allow this.

Allow custom formatting of map colorbar

---

pluma/stream/__init__.py
pluma/stream/microphone.py

Clock reference objects were initialized as a default mutable argument in the `Stream` base class. Since they were almost never explicitly set in the call to the base constructor, all streams shared a global state object and could therefore report an incorrect clock reference.
This has been fixed, and the `MicrophoneStream` clock reference also set to `None` to correctly indicate the absence of sample-by-sample synchronization for the raw audio data stream.

Ensure microphone clock reference is set to none

---

pluma/io/eeg.py
pluma/schema/__init__.py
pluma/stream/eeg.py

To allow a single schema to describe different collection conditions, and allow for quicker inspection of data quality, this PR introduces a nullable representation for EEG streams. If no NEDF files are found, a warning is issued, but the rest of the dataset will be imported successfully.

Allow empty EEG streams

---

pluma/export/streams.py
pluma/schema/__init__.py
pluma/stream/__init__.py
pluma/stream/accelerometer.py
pluma/stream/csv.py
pluma/stream/eeg.py
pluma/stream/empatica.py
pluma/stream/harp.py
pluma/stream/zeromq.py

To allow arbitrary referencing of the Harp data clock may require custom implementations to traverse the diverse object types which may represent a stream `data` attribute.
To allow for greater flexibility of implementations, e.g. in the case of EEG where we don't even control the reader class itself, this PR refactors the `reference_harp_to_ubx_time` method to use polymorphism, by introducing a new `rereference_clock_origin` in the base `Stream` class. This allows implementations to specify how exactly to apply a new arbitrary clock offset to the stream data.

Allow arbitrary clock referencing strategies

---

pluma/export/streams.py
pluma/schema/__init__.py
pluma/stream/__init__.py
pluma/stream/accelerometer.py
pluma/stream/csv.py
pluma/stream/eeg.py
pluma/stream/empatica.py
pluma/stream/harp.py
pluma/stream/zeromq.py

The refactoring in #42 and #44 introduced a critical regression since referencing time must always be done around an identical anchor point, rather than around the first time point of each series.
This PR references time around the first UBX time point, and applies a consistent offset to every data stream clock.

Ensure consistent clock reference

---

pluma/export/ogcapi/features.py
pluma/export/streams.py
pluma/preprocessing/resampling.py
pluma/stream/empatica.py
pluma/stream/harp.py

In order to facilitate data export and more powerful tooling for geospatial data manipulation, visualization and exploration, this PR refactors the entire geospatial preprocessing pipeline to use `geopandas.GeoDataFrame`. This allows replacing the use of `showmaps` with the interactive [`explore`](https://geopandas.org/en/stable/docs/user_guide/interactive_mapping.html) method of `geopandas`.
It also allows for more optimized dataframe merging and caching routines using directly `geopandas` functionality. The resampling strategy for data was checked for consistency with temporal resampling of geospatial points, i.e. each resampled row represents the average of data in the same time bin of the corresponding GNSS position.

Resample geospatial data using geopandas

---

pluma/export/maps.py
pluma/schema/__init__.py
pyproject.toml

Adds a new `exploremap` function wrapping the [`explore`](https://geopandas.org/en/stable/docs/user_guide/interactive_mapping.html) method with useful defaults for plotting the temporal progression of the path since timestamp indices are not supported out-of-the-box by `geopandas`.

Add support for interactive maps

---

pluma/io/empatica.py

Ensures that all native E4 timestamps are decoded using the UNIX epoch as detailed in the [empatica docs](https://support.empatica.com/hc/en-us/articles/202800715-Session-start-time-format-and-synchronization).
The UNIX epoch is Jan 1 1970, rather than the default Harp epoch (Jan 1 1904).

Decode E4 timestamps using correct epoch

---

pluma/io/empatica.py
pluma/stream/empatica.py

Continuous alignment of E4 timestamps with Harp has been complicated by burst transmission of messages through the Bluetooth serial link.
However, the E4 deltas themselves have low enough drift on the sampling frequencies of interest for recording durations up to one hour, so this PR provides an optional alignment based on the first message received.

Add support for aligning E4 hardware timestamps

---

pluma/export/ogcapi/features.py
pluma/export/streams.py
pluma/preprocessing/resampling.py

There was a regression in E4 data stream resampling due to multi-dimensional data frames. This PR generalizes multi-stream resampling to allow for multi-dimensional data frames, ensures naming of frames is correct, and includes E4 resampling in exported GeoJSON records, if available.

Add E4 multi-stream resampling to exported geojson

---

pluma/export/maps.py

This PR allows easier support for exploration of georeferenced custom data, by ensuring that the index is reset to prevent JSON serialization issues with timestamps. It also uses the series name as key to improve default colormap labeling.

Improve support for exploring custom geodata

---

pluma/export/streams.py

This PR adds the skin temperature stream to the resampled data included for the OGC API features collection. The data stream was already available so it was simply a matter of adding it to the resampled dictionary.

Add E4 skin temperature stream to exported geojson

---

pluma/export/streams.py
pluma/preprocessing/ecg.py
pluma/stream/ecg.py
pyproject.toml

For analysis purposes we always need to process and extract the heartrate in beats per minute from the raw ECG data. Currently this was done via a utility function that could be applied as a post-processing step to the raw data.
This PR introduces a specialized ECG stream reader that automatically computes the heartrate as part of data loading. When using the specialized stream the data will be organized in a hierarchical dotmap with the extracted metrics, similar to other compound data streams.
Fixes #58

Add specialized ECG stream with heartrate data

---

pluma/stream/zeromq.py

The current implementation for ZMQ streams is a generic binary loader for acquired raw binary frames. However, it didn't account for timestamping, which had to be resolved manually in the notebooks by joining two separate pieces of data as detailed in #56.
This PR refactors all ZMQ streams to derive from a common `ZmqStream` class which handles the timestamping logic automatically. It expects to receive a Harp event code in the constructor, which it will use to extract the counter value and subsequent join. The final data frame is a Harp timestamped data frame as with most other dataset streams.
Fixes #56

Refactor ZMQ streams to auto load harp timestamps

---

pluma/stream/zeromq.py

This PR does:
- In the heartrate stream rename the HardwareTime to HeartRate
- Rename `ProtocolPointToOriginWorld`, `ProtocolPointToOriginMap`.
- Add `ProtocolNewSceneStream`.
- Add `ProtocolItiStream`.
- Add `UnityGeoreferenceStream`.

Add missing unity streams 

---

pluma/stream/zeromq.py

Add a new component to the Glia eye tracking stream containing the data from VR Engine physics raycast hit points.

Add Raycast combined gaze info

---

pluma/schema/__init__.py
pluma/stream/zeromq.py

This PR introduces a new utility method `add_unity_georeference`, which computes an interpolated space-time table from a set of known correspondences between geolocation and VR cartesian coordinates recorded at acquisition time. This makes it easier to operate with the dataset in a similar way to outdoor walks.

Add interpolated georeference for VR walks

---

pluma/stream/eeg.py

EEG raw data is only rarely manipulated and explored directly as other data streams. However, it is instructive to have a reference implementation showing how to obtain a `DataFrame` object if necessary.

Add support for exporting EEG data as dataframe

---

pluma/export/ogcapi/records.py

The `utcnow` method has been deprecated in favor of using timezone aware objects. This PR updates the creation of record timestamps to use the new `timezone.utc` object.

Use timezone aware objects for record timestamps

---

pluma/schema/vr.py

This PR change the address space for VR sensors:
- VRTransform from 219 to1 180
- GeoReference 211 to 181
- ScreenCapture 220 to 182
- VR Experiment protocol [225-228] to [185-188]
- Glia [215-218] to [190-193]
- Update Readme
To avoid clashes with previously used harp addresses. 
Related to this https://github.com/emotional-cities/pluma-experiments/issues/95

Change address space for VR software harp messages

---

pluma/io/eeg.py

During EEG synchronization the process applies a linear regression between native EEG timestamps and harp timestamps. Currently this regression was applied indiscriminately across both protocol-specific and protocol-agnostic counters.
This PR automatically excludes all protocol-specific event markers from the regression to ensure only uniquely pseudo-random counters are included in the fit to prevent from inadvertent biases coming from specific protocol event logic.
Fixes #74

Ensure LSL synch markers are not event markers

---

pluma/schema/__init__.py

To match the one from UBX. This specific order is required by the way the resampling function accesses the navigation attributes using a range slice:
https://github.com/emotional-cities/pluma-analysis/blob/97aa3a43b4b9dd8c7a6f2f13c9761d0b41b452ca/pluma/preprocessing/resampling.py#L59-L60
In the future the resampling function could be made robust to different columns orders.
This is required to resample the data to GeoJSON.

Fix column order of nav data in add_unity_georeference

---

pluma/stream/ubx.py

To allow loading datasets where hardware clock synchronization with the GPS module failed or is unavailable, we extend the decoding of UTC time to use the `TIM_TP` (precision timepulse) message instead of `TIM_TM2` (input timemark) message.
This fallback decoding takes place in the cases where `calibrate_clock` has been set to `False`.

Allow decoding UTC time without calibration signal

---

pluma/templates/metadata_template.j2

The jinja2 template failed to handle multiple item lists correctly since it did not emit the comma separator. This short fix uses the [`loop.last`](https://jinja.palletsprojects.com/en/stable/templates/#for) control variable to emit separators except for the last item in the list.

Add comma separator when exporting multiple items

---

pluma/io/accelerometer.py
pluma/io/eeg.py
pluma/io/empatica.py
pluma/io/harp.py
pluma/io/ubx.py
pluma/stream/ecg.py
pluma/stream/eeg.py
pluma/stream/georeference.py
pluma/stream/harp.py
pluma/stream/ubx.py
pluma/sync/ubx2harp.py

This PR avoids duplication of Harp and E4 timestamp conversion code throughout the readers to make it easier to maintain any future changes.

Avoid duplicating timestamp calculations

---

pluma/schema/outdoor.py
pluma/schema/vr.py

Export of bio-signals acquired through the pluma board had been historically excluded since most were control counters and/or unprocessed / raw voltage data.
With the inclusion of the heartrate processor, the ECG stream on the pluma board is now meaningful. To include it in the exported geodata while keeping counters private, we introduce a new public non-excluded device "Pluma" and move both the ECG and GSR signals there.

Move pluma sensor features to separate device

---

pluma/templates/metadata_template.j2

This PR adds missing GeoJSON, GeoParquet and GeoPackage download links to the Jinja2 template used for exporting OGC API metadata records.

Add missing collection links

---

pyproject.toml

Sadly setuptools is required by heartpy due to a stray import statement. This is being tracked in the heartpy repo but not expected to be resolved anytime soon as the package appears not to be active.

Add missing dependency required by heartpy

---

pluma/stream/zeromq.py

For compatibility with latest NumPy 2.0+ we need to remove specific classes which have since become deprecated.

Remove deprecated numpy type

---

pyproject.toml

The `defusedxml` package is an optional MNE dependency which is however required for loading NEDF files. We therefore add it as an explicit dependency since NEDF is the main storage format for EEG data.

Add missing dependency for loading NEDF files

---

pluma/io/harp.py

NumPy 2.0 has more strict rules regarding casting and overflowing of operators. Here we recreate the changes in https://github.com/harp-tech/harp-python/pull/35 to ensure compatibility.
In the future we should really remove this custom code and simply install harp-python, but we need to think how to deal with the requirement for dealing with complex S3 bucket paths, so we defer this to a future update.

Avoid casting overflow for numpy compatibility

---

pluma/stream/glia.py
pluma/stream/pupil.py
pluma/stream/unity.py
pluma/stream/zeromq.py

Continuous alignment of ZMQ stream timestamps with the reference Harp clock has been complicated by burst transmission of messages through the TCP interface.
However, the underlying stream hardware timestamp deltas themselves have low drift on the sampling frequencies of interest for recording durations up to one hour, so this PR provides an optional alignment based on the first message received.

Add support for aligning ZMQ stream timestamps
